package net.lab0.grammar.kotlin

enum class KotlinHighlight {
    ANNOTATION,
    BACKGROUND,
    BRACKET,
    CLASS_DECLARATION,
    MODIFIER,
    CLASS_PARAMETER,
    COMMA,
    COMMENT,
    DEFAULT_TEXT,
    FUNCTION,
    INSTANCE_PROPERTY,
    KEYWORD,
    NUMBER,
    OPERATOR,
    SIMPLE_IDENTIFIER,
    STRING,
    STRING_ESCAPED_CHARACTER,
    ;
}
