package com.example.jetpackcomposeexplorer.code

enum class KotlinHighlight {
    ANNOTATION,
    CLASS_DECLARATION,
    CLASS_IDENTIFIER,
    MODIFIER,
    CLASS_PARAMETER,
    COMMA,
    COMMENT,
    DECIMAL_INTEGER,
    FUNCTION_DECLARATION,
    HEXADECIMAL_INTEGER,
    INSTANCE_PROPERTY,
    KEYWORD,
    SIMPLE_IDENTIFIER,
    STRING,
    VISIBILITY_MODIFIER
    ;
}
